CREATE DATABASE IF NOT EXISTS jeizi_production;
USE jeizi_production;

CREATE TABLE IF NOT EXISTS tournaments (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  slug VARCHAR(255) NOT NULL UNIQUE,
  game_type VARCHAR(50) NOT NULL,
  season VARCHAR(100) DEFAULT NULL,
  description TEXT DEFAULT NULL,
  status VARCHAR(50) DEFAULT 'upcoming',
  banner_url VARCHAR(500) DEFAULT NULL,
  logo_url VARCHAR(500) DEFAULT NULL,
  cover_image_url VARCHAR(1000) DEFAULT NULL,
  logo_image_url VARCHAR(1000) DEFAULT NULL,
  start_date DATE DEFAULT NULL,
  end_date DATE DEFAULT NULL,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tournament_modes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  tournament_id INT NOT NULL,
  code VARCHAR(50) NOT NULL,
  name VARCHAR(100) NOT NULL,
  competition_type VARCHAR(50) NOT NULL DEFAULT 'head_to_head',
  team_upload_enabled BOOLEAN DEFAULT true,
  is_active BOOLEAN DEFAULT true,
  sort_order INT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (tournament_id) REFERENCES tournaments(id) ON DELETE CASCADE,
  UNIQUE KEY uq_tournament_mode (tournament_id, code)
);

CREATE TABLE IF NOT EXISTS teams (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  shortname VARCHAR(50) DEFAULT NULL,
  logo VARCHAR(500) DEFAULT NULL,
  tournament_id INT DEFAULT NULL,
  tournament_mode_id INT DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (tournament_id) REFERENCES tournaments(id) ON DELETE SET NULL,
  FOREIGN KEY (tournament_mode_id) REFERENCES tournament_modes(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS matches (
  id INT AUTO_INCREMENT PRIMARY KEY,
  match_no INT DEFAULT 1,
  blue_team_id INT DEFAULT NULL,
  red_team_id INT DEFAULT NULL,
  mode VARCHAR(10) DEFAULT 'BO3',
  title VARCHAR(255) DEFAULT 'Match',
  queue_order INT DEFAULT 1,
  blue_score INT DEFAULT 0,
  red_score INT DEFAULT 0,
  status VARCHAR(50) DEFAULT 'queued',
  tournament_id INT DEFAULT NULL,
  tournament_mode_id INT DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (blue_team_id) REFERENCES teams(id) ON DELETE SET NULL,
  FOREIGN KEY (red_team_id) REFERENCES teams(id) ON DELETE SET NULL,
  FOREIGN KEY (tournament_id) REFERENCES tournaments(id) ON DELETE SET NULL,
  FOREIGN KEY (tournament_mode_id) REFERENCES tournament_modes(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS team_submissions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  team_name VARCHAR(255) NOT NULL,
  shortname VARCHAR(50) DEFAULT NULL,
  captain_name VARCHAR(255) NOT NULL,
  contact VARCHAR(255) NOT NULL,
  logo_url VARCHAR(500) DEFAULT NULL,
  notes TEXT DEFAULT NULL,
  status VARCHAR(20) DEFAULT 'pending',
  tournament_id INT DEFAULT NULL,
  tournament_mode_id INT DEFAULT NULL,
  approved_team_id INT DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (tournament_id) REFERENCES tournaments(id) ON DELETE SET NULL,
  FOREIGN KEY (tournament_mode_id) REFERENCES tournament_modes(id) ON DELETE SET NULL,
  FOREIGN KEY (approved_team_id) REFERENCES teams(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS app_settings (
  setting_key VARCHAR(100) PRIMARY KEY,
  setting_value TEXT,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS video_archives (
  id INT AUTO_INCREMENT PRIMARY KEY,
  tournament_id INT DEFAULT NULL,
  title VARCHAR(255) NOT NULL,
  description TEXT DEFAULT NULL,
  source_type VARCHAR(50) NOT NULL DEFAULT 'google_drive',
  source_url VARCHAR(1000) NOT NULL,
  embed_url VARCHAR(1000) DEFAULT NULL,
  thumbnail_url VARCHAR(1000) DEFAULT NULL,
  video_type VARCHAR(50) DEFAULT 'replay',
  recorded_at TIMESTAMP NULL DEFAULT NULL,
  sort_order INT DEFAULT 0,
  is_featured BOOLEAN DEFAULT false,
  is_published BOOLEAN DEFAULT true,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (tournament_id) REFERENCES tournaments(id) ON DELETE SET NULL
);